### ISSUE TITLE
Display in iFrame

### ISSUE THREAD

**Issue by madsem** [fidum/laravel-nova-vapor-ui-link#1]
Hey there,

thanks for this!

Just installed it and it works beautifully. I'm wondering though if it would be better if the whole UI is displayed in an iframe?
Kind of similar to https://github.com/GeneaLabs/nova-telescope

Thoughts?

**Comment by dmason30** [comment]
HI,

I think that would be a separate package. This repo was inspired by the [horizon](https://github.com/mad-web/nova-horizon-link) and [telescope ](https://github.com/mad-web/nova-telescope-link) nova link packages that do exactly what this package does and provide a simple link to the expected dashboard. 

It would be simple enough for you to clone the telescope package you linked above and tweak it to show the vapor ui dashboard instead if someone hasn't already done it. Then you can put that on novapackages.com for all to use 😄 

I would have no use for such a package so I am sorry but I won't be making it. 

Thanks for asking!

Dan
